[package]
name = "money"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
list_files_macro = "^0.1.0"
sankey = "^0.1.2"
svg = "0.10.0"
